openapi: 3.0.1
info:
  title: '@jupiterone/graph-cisco-ise'
  description: A graph conversion tool for Cisco ISE
  x-cortex-git:
    github:
      repository: JupiterOne/graph-cisco-ise
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-cisco-ise'
